apiVersion: v1
kind: Service
metadata:
  labels:
    app: mifos-community
  name: mifos-community
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: mifos-community
    tier: backend
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mifos-community
  labels:
    app: mifos-community
spec:
  selector:
    matchLabels:
      app: mifos-community
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mifos-community
        tier: backend
    spec:
      containers:
      - name: mifos-community
        image: openmf/community-app:latest
        resources:
          limits:
            cpu: "600m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "0.5Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 1
        ports:
        - containerPort: 80
          name: mifos-community
